### PR TITLE
pin base images to cortex-python-lib latest-develop for now. Pin cortex-python to 6.3.1a1

### PR DESCRIPTION
**Pull request by pkandarpa-cs**
We should ideally pin the base image to a tag generated off of main or staging. Leaving it at latest-develop for now. Need to update these files again when we have the 6.3.1 pyib release out on Pypi as a stable release

### CODE REVIEW

**Comment by pkandarpa-cs** [comment]
Slightly unsure if we still need the scuttle copy bits in the dockersfiles after @jgielstra-cs  recent PR to bundle scuttle in the cortex-python base image. @yreddy-CS  can you chime in?

**Comment by yreddy-CS** [comment]
> Slightly unsure if we still need the scuttle copy bits in the dockersfiles after @jgielstra-cs recent PR to bundle scuttle in the cortex-python base image. @yreddy-CS can you chime in?

The scuttle copy is not required anymore, these are already included as part of the base python image which is now being used

**Comment by pkandarpa-cs** [comment]
This PR is ready for review / or to be merged.

**Review by yreddy-CS — APPROVED** [review]

**Comment by pkandarpa-cs** [comment]
Local tests indicate all templates work fine. This PR is waiting for reviews before merge

**Review by ssingh-CS — APPROVED** [review]

**Pull request merged**
